"""`G16_CANDIDATE_COMPOSITION_SAFETY` (`TASK-081`): regression suite -- acceptance requirement 8.

Covers, per `TASK-081`'s own list: all 5 confounding traps (`T01`-`T05`), using their real or
counterfactual conditions exactly as `TASK-075`/`078`/`079` already reconstructed them (never
retyped by hand -- parsed from the already-committed
`docs/benchmark/task-075-t03-forensic-trace-raw.json`); a substitute for "the 6 historical `PASS`
candidates" (see the disclosed limitation below); and more than one domain (travel + `b2b_sales`,
per `TASK-070`'s own precedent).

**Disclosed limitation, matching the precedent `TASK-075`'s own `CODE_REVIEWER` review already
set (`TASKS.md` `TASK-075`, "Disclosed limitation of this review")**: the specific frozen
`artifacts/blind/task-073-official-20260829-001.*` (and every other frozen `candidates.json` this
project's various closing runs produced) is not present in this worktree -- `artifacts/` is
gitignored, and no prior session left one behind in this checkout. TASK-075's own report names
"the 6 real PASS candidates in `task-073-official-20260829-001`" as one of the negative controls a
future fix must be validated against, but does not enumerate their conditions in prose, and the
frozen file that would let this task reconstruct them programmatically (the same file `TASK-075`'s
own `CODE_REVIEWER` review already could not access, for the identical reason) is unavailable here
too. Rather than fabricate plausible-looking conditions, this suite instead exercises the real,
committed substitutes that genuinely are available without inventing data:

- **`CAND-014`/`CAND-007`/`CAND-015`** -- the *actual* real historical candidates `TASK-075`/`078`/
  `079` reconstructed and used as their own negative/positive controls, parsed from the same
  already-committed raw JSON `TASK-079`'s own script reads (never retyped).
- **`P01`** -- one of `synthetic_benchmark.py`'s own committed true-pattern definitions
  (`supplier=BlueWing AND discount_rate>=0.12 AND booking_lead_days<21`), a genuine, non-trap,
  three-atom compound rule with no shared apparent-feature overlap with any of the 5 traps, used
  here as a real (not fabricated), non-hand-typed stand-in for "a genuine multi-condition pattern
  that must not be misclassified `confound_like`".
- **`b2b_sales`'s own real `CAND-001`-shaped candidate** (`deal_size_usd<21811.14 AND
  product_line=Platform`), verbatim from the table `docs/benchmark/task-067-g06-diagnostic.md`
  already publishes (itself generated by `scripts/diagnose_g06_task065_b2b.py` from a frozen
  artifact this worktree also lacks -- the same limitation, disclosed the same way), used for the
  multi-domain requirement.

Split into two pytest classes, matching `TASK-081` control level 3's separation: `TestSafety`
assertions (cap-only) may never be satisfied by label choice; `TestDiagnostic` assertions (label
quality) may never be treated as a safety failure.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any

import pytest
from policy_analytics.outcomes import primary_outcome
from policy_analytics.outcomes.manifest_binding import outcome_definition_from_manifest
from policy_analytics.validation.apply import CandidateValidation, run_validation
from policy_analytics.validation.composition_safety import CompositionAtomClassification
from policy_analytics.validation.contract import LEVEL_ORDER, GateId, GateOutcome
from policy_schemas.domain import EvidenceLevel

pytestmark = pytest.mark.analytics

REPO_ROOT = Path(__file__).resolve().parents[2]
TRAVEL_DATASET = REPO_ROOT / "synthetic_data/analytical/travel-bookings-analytical-v1.1.0"
B2B_DATASET = REPO_ROOT / "synthetic_data_domains/b2b_sales/analytical/b2b_sales-analytical-v1.0.0"
TASK075_RAW = REPO_ROOT / "docs/benchmark/task-075-t03-forensic-trace-raw.json"
TRAVEL_DATASET_VERSION = "travel-bookings-analytical-v1.1.0"
TRAVEL_OUTCOME_VERSION = "1.1.0"


def _parse_condition_token(token: str) -> dict[str, Any]:
    feature, operator, value = token.split(" ", 2)
    try:
        coerced: object = float(value) if "." in value else int(value)
    except ValueError:
        coerced = {"True": True, "False": False}.get(value, value)
    return {"feature": feature, "operator": operator, "value": coerced}


def _trap_conditions(
    trap_id: str, *, counterfactual: bool, label_prefix: str | None = None
) -> list[dict[str, Any]]:
    """Real or counterfactual conditions for one trap, parsed from the committed
    `task-075-t03-forensic-trace-raw.json` -- the same source `TASK-079`'s own
    `_real_candidate_conditions_from_task075_raw` reads, reimplemented locally (read-only JSON
    parsing, not a code dependency on a `scripts/` module) so this test file has no import-path
    coupling to a diagnostic script.
    """
    payload = json.loads(TASK075_RAW.read_text(encoding="utf-8"))
    matches = [
        trace
        for trace in payload["trap_selection_traces"]
        if trace["trap_id"] == trap_id and trace["is_counterfactual"] is counterfactual
    ]
    if label_prefix is not None:
        matches = [m for m in matches if m["label"].startswith(label_prefix)]
    assert matches, f"no trace for {trap_id} (counterfactual={counterfactual}) in {TASK075_RAW}"
    return [_parse_condition_token(token) for token in matches[0]["condition"]]


def _run_one(
    dataset_root: Path,
    conditions: list[dict[str, Any]],
    outcome: Any,
    dataset_version: str,
    outcome_definition_version: str,
    label: str,
) -> CandidateValidation:
    with tempfile.TemporaryDirectory() as td:
        tmp_dir = Path(td)
        candidates_path = tmp_dir / "candidates.json"
        metrics_path = tmp_dir / "metrics.json"
        candidates_path.write_text(
            json.dumps(
                {
                    "status": "PERSISTED",
                    "outcome": {
                        "outcome_id": outcome.outcome_id,
                        "outcome_definition_version": outcome_definition_version,
                    },
                    "candidates": [
                        {
                            "candidate_id": label,
                            "conditions": conditions,
                            "outcome": outcome.outcome_id,
                        }
                    ],
                }
            ),
            encoding="utf-8",
        )
        metrics_path.write_text(json.dumps({"evaluated_hypotheses": 33_085}), encoding="utf-8")
        results, _ = run_validation(
            dataset_root=dataset_root,
            candidates_path=candidates_path,
            outcome=outcome,
            dataset_version=dataset_version,
            outcome_definition_version=outcome_definition_version,
            analysis_run_id=f"g16-regression-{label}",
            metrics_path=metrics_path,
        )
        return results[0]


# =====================================================================================
# Fixture data: the 5 traps' real/counterfactual conditions, and the two real substitutes.
# =====================================================================================

T01_COUNTERFACTUAL = _trap_conditions("T01", counterfactual=True)  # manager eq Manager 2 (k=1)
T02_COUNTERFACTUAL = _trap_conditions("T02", counterfactual=True)  # supplier eq Atlas (k=1)
T03_REAL_CAND014 = _trap_conditions("T03", counterfactual=False, label_prefix="CAND-014")  # k=2
T04_REAL_CAND007 = _trap_conditions("T04", counterfactual=False, label_prefix="CAND-007")  # k=3
T04_REAL_CAND015 = _trap_conditions("T04", counterfactual=False, label_prefix="CAND-015")  # k=2
T05_COUNTERFACTUAL = _trap_conditions("T05", counterfactual=True)  # manual_exception eq True (k=1)

P01_TRUE_PATTERN = [  # verbatim from synthetic_benchmark.py's own committed patterns list
    {"feature": "supplier", "operator": "eq", "value": "BlueWing"},
    {"feature": "discount_rate", "operator": "ge", "value": 0.12},
    {"feature": "booking_lead_days", "operator": "lt", "value": 21},
]

B2B_CAND001 = [  # verbatim from docs/benchmark/task-067-g06-diagnostic.md's own committed table
    {"feature": "deal_size_usd", "operator": "lt", "value": 21811.14},
    {"feature": "product_line", "operator": "eq", "value": "Platform"},
]
B2B_CAND009 = [
    {"feature": "company_size_band", "operator": "eq", "value": "small"},
    {"feature": "lead_score", "operator": "lt", "value": 76.0},
]


# =====================================================================================
# TestSafety -- cap-only assertions. Never fails on label choice.
# =====================================================================================


@pytest.mark.skipif(not TRAVEL_DATASET.exists(), reason="delivered analytical dataset not present")
class TestSafety:
    @pytest.mark.parametrize(
        "conditions,expected_k,label",
        [
            (T01_COUNTERFACTUAL, 1, "T01-counterfactual"),
            (T02_COUNTERFACTUAL, 1, "T02-counterfactual"),
            (T03_REAL_CAND014, 2, "T03-real-CAND014"),
            (T04_REAL_CAND007, 3, "T04-real-CAND007"),
            (T04_REAL_CAND015, 2, "T04-real-CAND015"),
            (T05_COUNTERFACTUAL, 1, "T05-counterfactual"),
        ],
    )
    def test_all_5_traps_g16_wiring_correct(
        self, conditions: list[dict[str, Any]], expected_k: int, label: str
    ) -> None:
        assert len(conditions) == expected_k
        result = _run_one(
            TRAVEL_DATASET,
            conditions,
            primary_outcome(),
            TRAVEL_DATASET_VERSION,
            TRAVEL_OUTCOME_VERSION,
            label,
        )
        gate_results = result.report.gate_results
        g16 = next(g for g in gate_results if g.gate_id is GateId.COMPOSITION_SAFETY)
        if expected_k <= 1:
            assert g16.satisfied is True
            assert g16.outcome is GateOutcome.PASS
        else:
            assert g16.outcome in (GateOutcome.PASS, GateOutcome.FAIL)
            if not g16.satisfied:
                level = result.report.evidence_level
                assert level is None or LEVEL_ORDER.index(level) <= LEVEL_ORDER.index(
                    EvidenceLevel.PREDICTIVE
                )

    def test_p01_true_pattern_g16_executes_and_caps_consistently(self) -> None:
        result = _run_one(
            TRAVEL_DATASET,
            P01_TRUE_PATTERN,
            primary_outcome(),
            TRAVEL_DATASET_VERSION,
            TRAVEL_OUTCOME_VERSION,
            "P01-true-pattern",
        )
        gate_results = result.report.gate_results
        g16 = next(g for g in gate_results if g.gate_id is GateId.COMPOSITION_SAFETY)
        assert g16.outcome in (GateOutcome.PASS, GateOutcome.FAIL)
        if not g16.satisfied:
            level = result.report.evidence_level
            assert level is None or LEVEL_ORDER.index(level) <= LEVEL_ORDER.index(
                EvidenceLevel.PREDICTIVE
            )

    @pytest.mark.skipif(not B2B_DATASET.exists(), reason="b2b_sales analytical dataset not present")
    @pytest.mark.parametrize(
        "conditions,label", [(B2B_CAND001, "b2b-CAND001"), (B2B_CAND009, "b2b-CAND009")]
    )
    def test_second_domain_b2b_sales_g16_wiring_correct(
        self, conditions: list[dict[str, Any]], label: str
    ) -> None:
        """`TASK-070`'s own multi-domain precedent: `G16` must not be a travel-specific mechanism
        -- it is computed entirely from the candidate's own condition tuple and the frame, with
        no dataset-specific logic anywhere (confirmed structurally by the diff in this task's own
        report; confirmed behaviorally here on a real second domain).
        """
        manifest = json.loads((B2B_DATASET / "manifest.json").read_text(encoding="utf-8"))
        outcome, outcome_version = outcome_definition_from_manifest(manifest, B2B_DATASET)
        result = _run_one(
            B2B_DATASET, conditions, outcome, manifest["dataset_version"], outcome_version, label
        )
        gate_results = result.report.gate_results
        g16 = next(g for g in gate_results if g.gate_id is GateId.COMPOSITION_SAFETY)
        assert g16.outcome in (GateOutcome.PASS, GateOutcome.FAIL)
        assert g16.satisfied is False  # both b2b conditions above are k=2 compound
        level = result.report.evidence_level
        predictive_rank = LEVEL_ORDER.index(EvidenceLevel.PREDICTIVE)
        assert level is None or LEVEL_ORDER.index(level) <= predictive_rank


# =====================================================================================
# TestDiagnostic -- label-quality assertions on real data. A failure here is a diagnostic
# finding worth investigating, never a safety failure (see test_g16_safety.py for the
# safety-critical suite; this class asserts nothing about capping).
# =====================================================================================


def _confound_like_atoms(atoms: list[dict[str, Any]]) -> list[dict[str, Any]]:
    target = CompositionAtomClassification.CONFOUND_LIKE.value
    return [atom for atom in atoms if atom["classification"] == target]


@pytest.mark.skipif(not TRAVEL_DATASET.exists(), reason="delivered analytical dataset not present")
class TestDiagnostic:
    def test_p01_true_patterns_own_atoms_are_not_labeled_confound_like(self) -> None:
        """`P01`'s three atoms (`supplier`, `discount_rate`, `booking_lead_days`) are, by this
        pattern's own construction in `synthetic_benchmark.py`, jointly defining one true causal
        rule -- none is a confound of the others. `indeterminate` is the correct, expected
        outcome for all three (per `ADR-077`/`078`, this design never *asserts* "no confound" --
        it only ever withholds the positive `confound_like` claim). `confound_like` here would be
        a diagnostic finding worth investigating, not a safety failure.
        """
        result = _run_one(
            TRAVEL_DATASET,
            P01_TRUE_PATTERN,
            primary_outcome(),
            TRAVEL_DATASET_VERSION,
            TRAVEL_OUTCOME_VERSION,
            "P01-diagnostic",
        )
        atoms = result.diagnostics["composition_safety_atoms"]
        assert len(atoms) == 3
        offenders = _confound_like_atoms(atoms)
        assert offenders == [], f"P01's own atoms wrongly classified confound_like: {offenders}"

    def test_t04_real_cand007_structural_exclusion_not_labeled_confound_like(self) -> None:
        """`CAND-007` (`T04`, `k=3`) is `TASK-075`'s own "correct, structurally-exclusion-based
        handling" case -- a genuine `P06` recovery whose own condition features happen to equal
        `T04`'s true confounders, so `G02`'s circularity guard (not `G06`'s coverage floor)
        excludes them. `G16`'s own leave-one-out check has no such circularity concern (it never
        adjusts a candidate for its own condition), so this only asserts the diagnostic
        expectation that a genuine recovery's own atoms are not spuriously flagged
        confound_like -- again, `indeterminate` either way caps identically and would not be a
        safety failure.
        """
        result = _run_one(
            TRAVEL_DATASET,
            T04_REAL_CAND007,
            primary_outcome(),
            TRAVEL_DATASET_VERSION,
            TRAVEL_OUTCOME_VERSION,
            "T04-CAND007-diagnostic",
        )
        atoms = result.diagnostics["composition_safety_atoms"]
        assert len(atoms) == 3
        offenders = _confound_like_atoms(atoms)
        assert offenders == [], (
            f"CAND-007's own atoms wrongly classified confound_like: {offenders}"
        )
